### Q4 Implement data preprocessing (for handle missing values by deletion and imputation, for handle missing values by LabelEncoder & OneHotEncoder) using scikitlearn.


In [6]:
import pandas as pd
df=pd.read_csv('../Datasets/basics_data.csv') # read data
print(df) # print DF
print(df.size) # df size
print('Rows=',df.shape[0])
print('Cols=',df.shape[1])
print(df.shape) # shape
print(df.values) # numpy array
df.to_csv('abc.csv',index=False)
print('DF has written sucessfully')

    F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
7    7   8   9   NaN  11.0  12      UK  green  Female
8    8   9  10   NaN  12.0  13     IND  green  Female
9    9  10  11  12.0  13.0  14      UK  green  Female
10  10  11  12  13.0   NaN  15     IND   blue  Female
11  11  12  13  14.0   NaN  16      UK   blue  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female
126
Rows= 14
Cols= 9
(14, 9)
[[0 1 2 3.0 4.0 5 'IND' 'red' 'Male']
 [1 2 3 4.0 5.0 6 'UK' 'red' 'Male']
 [2 3 4 5.0 6.0 7 'IND' 'red' 'Male']
 [3 4 5 6.0 7.0 8 'UK' 'red' 'Male']
 [4 5 6 7.0

In [2]:
####### check for missing values and DELETE
print(df.isna().sum())
df1=df.dropna() # delete all missing values
print(df1)
print(df1.isna().sum())

F1         0
F2         0
F3         0
F4         2
F5         2
F6         0
Country    0
Color      0
Target     0
dtype: int64
    F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
9    9  10  11  12.0  13.0  14      UK  green  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female
F1         0
F2         0
F3         0
F4         0
F5         0
F6         0
Country    0
Color      0
Target     0
dtype: int64


In [3]:
######### Ordinal data [dictionary mapping]
df3=df.drop(['Color'],axis=1)

map_name={'IND':1,'UK':2}
df3['Country']=df3['Country'].map(map_name)
dict_tar={'Male':0,'Female':1}
df3['Target']=df3['Target'].map(dict_tar)
print(df3)



    F1  F2  F3    F4    F5  F6  Country  Target
0    0   1   2   3.0   4.0   5        1       0
1    1   2   3   4.0   5.0   6        2       0
2    2   3   4   5.0   6.0   7        1       0
3    3   4   5   6.0   7.0   8        2       0
4    4   5   6   7.0   8.0   9        1       0
5    5   6   7   8.0   9.0  10        2       0
6    6   7   8   9.0  10.0  11        1       0
7    7   8   9   NaN  11.0  12        2       1
8    8   9  10   NaN  12.0  13        1       1
9    9  10  11  12.0  13.0  14        2       1
10  10  11  12  13.0   NaN  15        1       1
11  11  12  13  14.0   NaN  16        2       1
12  12  13  14  15.0  16.0  17        1       1
13  13  14  15  16.0  17.0  18        2       1


In [4]:
#Handling Missing values by imputation
import numpy as np
from sklearn.impute import SimpleImputer
#  #mean, meadian,most_frequent,constant, fill_value=0
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')#,fill_value=0)
df3=imp_mean.fit_transform(df3)
df3

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         5.        ,  1.        ,  0.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ,
         6.        ,  2.        ,  0.        ],
       [ 2.        ,  3.        ,  4.        ,  5.        ,  6.        ,
         7.        ,  1.        ,  0.        ],
       [ 3.        ,  4.        ,  5.        ,  6.        ,  7.        ,
         8.        ,  2.        ,  0.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  8.        ,
         9.        ,  1.        ,  0.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        10.        ,  2.        ,  0.        ],
       [ 6.        ,  7.        ,  8.        ,  9.        , 10.        ,
        11.        ,  1.        ,  0.        ],
       [ 7.        ,  8.        ,  9.        ,  9.33333333, 11.        ,
        12.        ,  2.        ,  1.        ],
       [ 8.        ,  9.        

## Encoding

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# Select categorical columns
dfOHE=df.copy()
categorical_cols = df.select_dtypes(include=['object']).columns

# Create an instance of LabelEncoder for each categorical column
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()

    # Fit the encoder to the data
    label_encoders[col].fit(df[col])

    # Transform the data by replacing categorical values with encoded values
    dfOHE[col] = label_encoders[col].transform(df[col])
    
print(dfOHE)


    F1  F2  F3    F4    F5  F6  Country  Color  Target
0    0   1   2   3.0   4.0   5        0      2       1
1    1   2   3   4.0   5.0   6        1      2       1
2    2   3   4   5.0   6.0   7        0      2       1
3    3   4   5   6.0   7.0   8        1      2       1
4    4   5   6   7.0   8.0   9        0      1       1
5    5   6   7   8.0   9.0  10        1      1       1
6    6   7   8   9.0  10.0  11        0      1       1
7    7   8   9   NaN  11.0  12        1      1       0
8    8   9  10   NaN  12.0  13        0      1       0
9    9  10  11  12.0  13.0  14        1      1       0
10  10  11  12  13.0   NaN  15        0      0       0
11  11  12  13  14.0   NaN  16        1      0       0
12  12  13  14  15.0  16.0  17        0      0       0
13  13  14  15  16.0  17.0  18        1      0       0


In [6]:
#### SKLEARN OHE
df=pd.read_csv('basics_data.csv') # read data
print(df)
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
x=ohe.fit_transform(df[['Color']].values).toarray()
print(x)
df1=pd.DataFrame(x,columns=ohe.categories_)
print(df1)
df2=pd.concat([df,df1],axis=1)
df2=df2.drop(['Color'],axis=1)
print(df2)

    F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
7    7   8   9   NaN  11.0  12      UK  green  Female
8    8   9  10   NaN  12.0  13     IND  green  Female
9    9  10  11  12.0  13.0  14      UK  green  Female
10  10  11  12  13.0   NaN  15     IND   blue  Female
11  11  12  13  14.0   NaN  16      UK   blue  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
   blue green  red
0 